### ISSUE TITLE
Cannot understand the purpose of a User Type

### ISSUE THREAD

**Issue by thomasdom** [vanilophp/framework#10]
![screenshot-2018-3-21 editing thomas vanilo 1](https://user-images.githubusercontent.com/12234140/37729457-52428118-2d3d-11e8-93c8-4fd3443c77dc.png)

I don't understand the benefits of adding a User type in User edit form if there are roles that can be assigned to users. Can you explain me your vision please ?

**Comment by fulopattila122** [comment]
Yeah, good question. Maybe they could be removed completely.

The basic idea is that admin and client accounts should not be mixed together.
The list of types can be extended so you may want to create "api" user type for example.

These types can be considered as "rough" distinction between various essential user types that have completely different scopes.

Roles and permissions are for fine tuned access management like "Product manager", "Order processing", "Campaign manager", etc.

User can only have one type but can have multiple roles assigned.
