### ISSUE TITLE
Payments are missing a status.

### ISSUE THREAD

**Issue by addgod** [vanilophp/framework#103]
Since by law, at least in the country where I am from, you are not allowed to withdraw the money from the customers card, until the item is shipped, then PaymenStatus should really have a AUTHORIZED status as well. 

So you can authorize the money on a customers card, and then when you ship your items, then you can mark the payment as paid.

**Comment by fulopattila122** [comment]
Yeah, makes sense. Can you please submit a PR in the vanilophp/payment repo?

**Comment by addgod** [comment]
Sure. Just have to finish some tasks and I will do it.

**Comment by addgod** [comment]
Done.
