### ISSUE TITLE
composer require vanilo/framework , laravel v8.5.14 Installation failed

### ISSUE THREAD

**Issue by ayhanbaris** [vanilophp/framework#105]
ayhan@mvk ~ % composer create-project --prefer-dist laravel/laravel vaniloapp
Creating a "laravel/laravel" project at "./vaniloapp"
Installing laravel/laravel (v8.5.14)

ayhan@mvk ~ % cd vaniloapp
ayhan@mvk vaniloapp % composer require vanilo/framework
Using version ^1.2 for vanilo/framework
./composer.json has been updated
Running composer update vanilo/framework
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - vanilo/framework[1.2.0, ..., 1.2.x-dev] require laravel/framework ~5.5|~6.0|~7.0 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.12).
    - Root composer.json requires vanilo/framework ^1.2 -> satisfiable by vanilo/framework[1.2.0, 1.2.1, 1.2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by fulopattila122** [comment]
Use Vanilo 2.0+:

```
composer require vanilo/framework "^2.1"
```

**Comment by ayhanbaris** [comment]
thank you, i am tying...

**Comment by fulopattila122** [comment]
Btw, what PHP version do you have?

**Comment by ayhanbaris** [comment]
i m upgrading now to php 7.4


ayhan@mvk vaniloapp % php -v
PHP 7.3.25 (cli) (built: Nov 30 2020 14:36:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.25, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.25, Copyright (c) 1999-2018, by Zend Technologies
    
    
ayhan@mvk vaniloapp % composer require vanilo/framework "^2.1"
[InvalidArgumentException]
  Package vanilo/framework at version ^2.1 has a PHP requirement incompatible
   with your PHP version, PHP extensions and Composer version

**Comment by fulopattila122** [comment]
Yep, Vanilo 2 requires PHP 7.4 or 8.0.
If you stick to PHP 7.3 then only Vanilo 1.2 is available - or - all the standalone modules without the framework glue.

**Comment by ayhanbaris** [comment]
done.

ayhan@mvk vaniloapp % **composer require vanilo/framework "^2.1"**
./composer.json has been updated
Running composer update vanilo/framework
Loading composer repositories with package information
Updating dependencies
Lock file operations: 38 installs, 0 updates, 0 removals
  - Locking cocur/slugify (v4.0.0)
  - Locking cviebrock/eloquent-sluggable (8.0.5)
  - Locking diglactic/laravel-breadcrumbs (v6.1.0)
  - Locking doctrine/cache (1.10.2)
  - Locking doctrine/dbal (2.12.1)
  - Locking doctrine/event-manager (1.1.1)
  - Locking intervention/image (2.5.1)
  - Locking konekt/acl (1.5.0)
  - Locking konekt/address (2.1.0)
  - Locking konekt/appshell (2.2.0)
  - Locking konekt/concord (1.10.1)
  - Locking konekt/customer (2.1.0)
  - Locking konekt/enum (3.1.0)
  - Locking konekt/enum-eloquent (1.7.0)
  - Locking konekt/gears (1.7.0)
  - Locking konekt/laravel-migration-compatibility (1.4.1)
  - Locking konekt/menu (1.8.2)
  - Locking konekt/user (2.3.0)
  - Locking laracasts/flash (3.2)
  - Locking laravelcollective/html (v6.2.1)
  - Locking league/glide (1.7.0)
  - Locking maennchen/zipstream-php (2.1.0)
  - Locking myclabs/php-enum (1.8.0)
  - Locking spatie/image (1.10.4)
  - Locking spatie/image-optimizer (1.3.2)
  - Locking spatie/laravel-medialibrary (9.4.4)
  - Locking spatie/temporary-directory (1.3.0)
  - Locking vanilo/cart (2.1.1)
  - Locking vanilo/category (2.1.0)
  - Locking vanilo/channel (2.1.0)
  - Locking vanilo/checkout (2.1.0)
  - Locking vanilo/contracts (2.1.0)
  - Locking vanilo/framework (2.1.1)
  - Locking vanilo/order (2.2.0)
  - Locking vanilo/payment (2.1.1)
  - Locking vanilo/product (2.1.0)
  - Locking vanilo/properties (2.1.1)
  - Locking vanilo/support (2.1.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 38 installs, 0 updates, 0 removals
  - Downloading cocur/slugify (v4.0.0)
  - Downloading diglactic/laravel-breadcrumbs (v6.1.0)
  - Downloading intervention/image (2.5.1)
  - Downloading konekt/enum (3.1.0)
  - Downloading konekt/enum-eloquent (1.7.0)
  - Downloading konekt/concord (1.10.1)
  - Downloading konekt/acl (1.5.0)
  - Downloading konekt/laravel-migration-compatibility (1.4.1)
  - Downloading konekt/address (2.1.0)
  - Downloading konekt/user (2.3.0)
  - Downloading konekt/customer (2.1.0)
  - Downloading konekt/gears (1.7.0)
  - Downloading konekt/menu (1.8.2)
  - Downloading laracasts/flash (3.2)
  - Downloading laravelcollective/html (v6.2.1)
  - Downloading spatie/temporary-directory (1.3.0)
  - Downloading spatie/image-optimizer (1.3.2)
  - Downloading league/glide (1.7.0)
  - Downloading spatie/image (1.10.4)
  - Downloading vanilo/contracts (2.1.0)
  - Downloading vanilo/support (2.1.1)
  - Downloading cviebrock/eloquent-sluggable (8.0.5)
  - Downloading vanilo/properties (2.1.1)
  - Downloading vanilo/product (2.1.0)
  - Downloading vanilo/payment (2.1.1)
  - Downloading vanilo/order (2.2.0)
  - Downloading vanilo/checkout (2.1.0)
  - Downloading vanilo/channel (2.1.0)
  - Downloading vanilo/category (2.1.0)
  - Downloading vanilo/cart (2.1.1)
  - Downloading spatie/laravel-medialibrary (9.4.4)
  - Downloading konekt/appshell (2.2.0)
  - Downloading vanilo/framework (2.1.1)
  - Installing cocur/slugify (v4.0.0): Extracting archive
  - Installing diglactic/laravel-breadcrumbs (v6.1.0): Extracting archive
  - Installing doctrine/event-manager (1.1.1): Extracting archive
  - Installing doctrine/cache (1.10.2): Extracting archive
  - Installing doctrine/dbal (2.12.1): Extracting archive
  - Installing intervention/image (2.5.1): Extracting archive
  - Installing konekt/enum (3.1.0): Extracting archive
  - Installing konekt/enum-eloquent (1.7.0): Extracting archive
  - Installing konekt/concord (1.10.1): Extracting archive
  - Installing konekt/acl (1.5.0): Extracting archive
  - Installing konekt/laravel-migration-compatibility (1.4.1): Extracting archive
  - Installing konekt/address (2.1.0): Extracting archive
  - Installing konekt/user (2.3.0): Extracting archive
  - Installing konekt/customer (2.1.0): Extracting archive
  - Installing konekt/gears (1.7.0): Extracting archive
  - Installing konekt/menu (1.8.2): Extracting archive
  - Installing laracasts/flash (3.2): Extracting archive
  - Installing laravelcollective/html (v6.2.1): Extracting archive
  - Installing myclabs/php-enum (1.8.0): Extracting archive
  - Installing maennchen/zipstream-php (2.1.0): Extracting archive
  - Installing spatie/temporary-directory (1.3.0): Extracting archive
  - Installing spatie/image-optimizer (1.3.2): Extracting archive
  - Installing league/glide (1.7.0): Extracting archive
  - Installing spatie/image (1.10.4): Extracting archive
  - Installing vanilo/contracts (2.1.0): Extracting archive
  - Installing vanilo/support (2.1.1): Extracting archive
  - Installing cviebrock/eloquent-sluggable (8.0.5): Extracting archive
  - Installing vanilo/properties (2.1.1): Extracting archive
  - Installing vanilo/product (2.1.0): Extracting archive
  - Installing vanilo/payment (2.1.1): Extracting archive
  - Installing vanilo/order (2.2.0): Extracting archive
  - Installing vanilo/checkout (2.1.0): Extracting archive
  - Installing vanilo/channel (2.1.0): Extracting archive
  - Installing vanilo/category (2.1.0): Extracting archive
  - Installing vanilo/cart (2.1.1): Extracting archive
  - Installing spatie/laravel-medialibrary (9.4.4): Extracting archive
  - Installing konekt/appshell (2.2.0): Extracting archive
  - Installing vanilo/framework (2.1.1): Extracting archive
