### ISSUE TITLE
Http admin controllers

### ISSUE THREAD

**Issue by mfilin** [vanilophp/framework#116]
hi
how we can extend the functions of admins controllers?
for example, if i want to move properties from show-view to edit-view, then i need to add taxonomies 
parametres into vendor\vanilo\framework\src\Http\Controllers\ProductController.php ...

**Comment by edotxxx** [comment]
Hi!

[https://konekt.dev/concord/1.9/controllers](https://konekt.dev/concord/1.9/controllers
)
In short:

Create your controller:
`
class ProductController extends \Vanilo\Framework\Http\Controllers\ProductController
`

Then in your RouteServiceProvider register your new controller:

```
        $route = Route::getRoutes()->getByName('vanilo.product.store');
        $routeAction = array_merge($route->getAction(), [
            'uses'       => '\App\Http\Controllers\Admin\ProductController@store',
            'controller' => '\App\Http\Controllers\Admin\ProductController@store',
        ]);
        $route->setAction($routeAction);
```

**Comment by mfilin** [comment]
thx :) good solution
