### ISSUE TITLE
Vanilo v.3 - no vanilo/admin package

### ISSUE THREAD

**Issue by edotxxx** [vanilophp/framework#117]
Hi!
Congrats with v.3 release!

Package "vanilo/admin" is not present in packagist.

**Comment by fulopattila122** [comment]
The 3.x-dev version is available when your application has the following in its composer.json:

```json
{
      "minimum-stability": "dev",
      "prefer-stable": true
}
```

So then using `composer req vanilo/admin ^3.0` should work

**Comment by noge075** [comment]
Hey!

I just installed and got an error for the admin when I try to open the route:
![image](https://user-images.githubusercontent.com/16837514/165598621-f68351e3-cf9e-4cdd-8eee-943b426389ea.png)

My composer file:
`"require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.2",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "laravel/ui": "^3.4",
        "vanilo/admin": "3.x-dev",
        "vanilo/framework": "^3.0"
    },`

Thanks!

**Comment by fulopattila122** [comment]
Please check the installation steps here: https://vanilo.io/docs/3.x/admin-installation
From what I see, you need to add the modules to `config/concord.php` described on the linked page

**Comment by fulopattila122** [comment]
@noge075 did it work?
