### ISSUE TITLE
 Class 'Vanilo\Foundation\Providers\ModuleServiceProvider' not found

### ISSUE THREAD

**Issue by the-Tofiq** [vanilophp/framework#118]
Edit config/concord.php and add this content:

<?php

return [
    'modules' => [
        Vanilo\Foundation\Providers\ModuleServiceProvider::class
    ]
];

**Comment by SigalZ** [comment]
Having the same problem. Can't use this framework.

**Comment by fulopattila122** [comment]
Could you please give me more details about how did you install it, which version do you use, etc?

**Comment by SigalZ** [comment]
I followed the installation instructions on the web site: https://vanilo.io/docs/3.x/installation
It fails on this step:
The following [Concord](https://vanilo.io/docs/3.x/concord) modules should be installed now:

php artisan concord:modules -a

**Comment by fulopattila122** [comment]
OK, I take a look at it RN.
Could you please tell me what PHP version are you using? Maybe the OS and/or environment?

**Comment by fulopattila122** [comment]
Vanilo 3 requires PHP 8, ie. won't install on PHP 7.x.
What is the content (listing) of the `vendor/vanilo` folder?

**Comment by fulopattila122** [comment]
@the-Tofiq are you maybe also using Windows + WAMP and/or PHP < 8.0?

**Comment by SigalZ** [comment]
Thank you. First I would like to apologize, I did miss the php version part, going to install a newer wamp version and try again.
The vendor/vanilo folder attached
![Vanilo-Folder](https://user-images.githubusercontent.com/7089214/165469369-fcbe0a30-1dad-484a-b693-2d1d9897c0a2.png)
.

**Comment by fulopattila122** [comment]
Ah OK, this is a Vanilo 2 installation, because that's compatible with PHP 7.x, and composer falls back to that.
You have two choices:
1. Keep PHP 7 and follow the instructions for Vanilo 2: https://vanilo.io/docs/2.x/installation
2. Upgrade to PHP 8, and reinstall the app from scratch and keep with Vanilo 3.

I would recommend the second choice.

Ps.: Thanks for the report, I will update the documentation accordingly

**Comment by fulopattila122** [comment]
> If I may suggest, it would be nice to have an online demo and a support option on your web site.

Thank you, we'll do both, these have been on our plate for a while.
What would be your preferred way of getting support?

**Comment by SigalZ** [comment]
@fulopattila122 For me a forum is a great way for getting support. 
Have a wonderful day.

**Comment by fulopattila122** [comment]
> For me a forum is a great way for getting support.

https://github.com/vanilophp/framework/discussions
I'll add the link to the site
