### ISSUE TITLE
Question: Release info on 3.1

### ISSUE THREAD

**Issue by towoju5** [vanilophp/framework#119]
Please is their any update on the release date for version 3.1? am working on a project that will require the MasterProduct so i will like to know if you have any news on this.

**Comment by dcbndev** [comment]
waiting for any updates, as well.

**Comment by neolinks** [comment]
any updates?

**Comment by towoju5** [comment]
> any updates?

There was a new update 2 days ago.

**Comment by neolinks** [comment]
> > any updates?
> 
> There was a new update 2 days ago.

haven't seen anything about the MasterProduct

**Comment by danpalmieri** [comment]
up

**Comment by danpalmieri** [comment]
https://github.com/vanilophp/framework/commit/9563d4ac80382721222d9b64d50e25c0c9a9feac
👀
