### ISSUE TITLE
Does Vanilo support nulti-vendor/multi-tenancy?

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [vanilophp/framework#12]
I'm very interested in Vanilo, but I have a question: does it support multi-vendor/multi-tenancy?

I want to make a way in that any user of my system can create your own store.

Thanks

**Comment by fulopattila122** [comment]
No, there's no such thing on the roadmap so far: https://vanilo.io/docs/0.2/roadmap
Right now you need to implement that yourself.

This feature might be implemented at a later point as an extension, but most probably won't be the part of the core.
