### ISSUE TITLE
Correct select from db

### ISSUE THREAD

**Issue by mfilin** [vanilophp/framework#121]
how I can correct and simple select data from db of products with category?
my current solution is it

```
$products = $this->productFinder
                        ->getQueryBuilder()
                        ->select('products.*',
                                DB::raw('
                                    (SELECT
                                        `model_taxons`.`taxon_id`
                                        FROM 
                                            `model_taxons`
                                        INNER join `taxons` on `model_taxons`.`taxon_id` = `taxons`.`id`
                                        where products.`id` = `model_taxons`.`model_id` and `model_taxons`.`model_type` = \'product\'
                                            AND `taxons`.taxonomy_id = 2
                                        limit 1
                                    ) AS category_id
                                '),                                
                        )
                        ->whereIn('state', $statuses)
                        ->orderby('created_at', 'DESC')
                        ->paginate(20);
```

but it's very big and if i need add new field category_name - then query sets new big size :(

can help me?

**Comment by fulopattila122** [comment]
What do you want to achive?

**Comment by mfilin** [comment]
now i need to display data of category product in grid list

**Comment by fulopattila122** [comment]
Sorry, I'm not 100% sure what you want to achieve.

1) Do you want to get a list of products within a category?
or
2) Do you want to display all products so that their assigned categories are retrieved?

**Comment by mfilin** [comment]
no, i need to display category name in product row...
![image](https://user-images.githubusercontent.com/1892629/169771884-6400f51f-ca09-40df-976e-191ea29a6b1e.png)

**Comment by fulopattila122** [comment]
Got it, coming back with a solution shortly.

**Comment by fulopattila122** [comment]
So I've made this as an experiment:

**Controller:**

```php
<?php

namespace App\Http\Controllers;

use Vanilo\Foundation\Search\ProductFinder;

class HomeController extends Controller
{
    public function __construct(
        private ProductFinder $finder
    ) {
    }

    public function show()
    {
        $products = $this->finder->getQueryBuilder()->with('taxons')->get();

        return view('home', ['products' => $products]);
    }
}
```

**View:**

```blade
@extends('layouts.default')

@section('title', 'Home')

@section('content')
<div class="container mx-auto">
    <h1 class="font-bold text-3xl">Featured Products</h1>
    <div class="grid md:grid-cols-4 mt-4">
        @foreach($products as $product)
            <div>
                <h3 class="text-2xl font-bold">{{ $product->title }}</h3>
                @foreach($product->taxons as $taxon)
                    <h4>{{ $taxon->name }}</h4>
                @endforeach
            </div>
        @endforeach
    </div>
</div>
@endsection
```

**Having these products in admin:**

![image](https://user-images.githubusercontent.com/1162360/169778837-b97842d4-182e-49a0-bb8e-7dc823aa6fcf.png)

**Got this result:**

![image](https://user-images.githubusercontent.com/1162360/169779148-4a8b2ad0-1895-4039-a995-e0e8341c3eab.png)

It's also effective, as it uses 2 queries in total:

![image](https://user-images.githubusercontent.com/1162360/169779319-1e88b7a3-89c1-493a-9411-56d70596e96c.png)

**Comment by fulopattila122** [comment]
Now, if you want to separate brands and categories, then the 2nd part is coming shortly...

**Comment by fulopattila122** [comment]
If you know that you have brands and categories, you can make use of the [collection filters](https://laravel.com/docs/9.x/collections#method-filter) in the blade view:

**Controller:**

```php
    public function show()
    {
        return view('home',  [
            'products' => $this->finder->getQueryBuilder()->with('taxons')->get(),
            'brand' => Taxonomy::findOneBySlug('brand'),
            'category' => Taxonomy::findOneBySlug('category'),
        ]);
    }
```

**Blade View:**

```blade
    <h1 class="font-bold text-3xl">Featured Products</h1>
    <div class="grid md:grid-cols-4 mt-4">
        @foreach($products as $product)
            <div>
                <h3 class="text-2xl font-bold">{{ $product->title }}</h3>
                <h4>Brand: {{ $product->taxons->filter(fn($taxon) => $taxon->taxonomy_id === $brand->id)->first()->name}}</h4>
                <h4>Categories: {{ $product->taxons->filter(fn($taxon) => $taxon->taxonomy_id === $category->id)->implode('name', ', ')}}</h4>

            </div>
        @endforeach
    </div>
```

> I assumed, that you always have one brand assigned and that there can be multiple categories. But this is arbitrary of course.

**Result + Queries**:

![image](https://user-images.githubusercontent.com/1162360/169781781-6a713a8b-f2b7-4326-a1a9-819b54fe06b9.png)

**Comment by fulopattila122** [comment]
Did it answer your question?

**Comment by mfilin** [comment]
sorry, i got answer :) thx
i am was gone to work with head )) i think thats all we need.

**Comment by fulopattila122** [comment]
Cool! :star2: 

Thanks for the question, it shed the light on the fact, that the product finder has zero documentation.
I created a task for that and we'll update the docs, and I'll make a how-to-article from this solution.

Have a great day :+1:
