### ISSUE TITLE
Customers aren't tying into orders

### ISSUE THREAD

**Issue by KodeStar** [vanilophp/framework#124]
So I created some orders and set the user id to 3, on user id 3 the customer_id is set to 14, customer 14 is my only customer. Looking at the CRM it says I have 1 customer but that customer has 0 orders.

**Comment by fulopattila122** [comment]
That is not a "lookup" field, but was designed to be updated from events. We typically update them with a listener bound to the [OrderCreated](https://github.com/vanilophp/framework/blob/master/src/Order/Events/OrderWasCreated.php) event.
