### ISSUE TITLE
many props value for prop

### ISSUE THREAD

**Issue by mfilin** [vanilophp/framework#125]
hi, i am dont understand why method $product->propertyValues()->sync(data) dont work with data
`[
5 => 111, 222, 333
]`

and i see that in DB is only one record 111

:((((

**Comment by mfilin** [comment]
its my mistake, sorry...

**Comment by fulopattila122** [comment]
Only one property value per property can be assigned. Ie. a Shoe can be either size of 42 or 43, but not both.

In turn, multiple taxons can be assigned to an entity (product).
