### ISSUE TITLE
Route [appshell.xoxoxo.xoxo] not found

### ISSUE THREAD

**Issue by towoju5** [vanilophp/framework#134]
whenever i tried to run php artisan serve i get the error appshell route not found[ ex: appshell.customer.index  and co. none of the routes is working ]. please anyone ever experience this? or anyone knows how i can fix this please?
Laravel 9
vanilo 3
vanilo admin package

**Comment by fulopattila122** [comment]
You need to add the modules to concord.php as stated here in the 3rd step: https://vanilo.io/docs/3.x/admin-installation

**Comment by towoju5** [comment]
Thanks for the response, i did but made a mistake. so stupid of me. 

Thanks a lot for the hardwork.
