### ISSUE TITLE
Extending values in app setting

### ISSUE THREAD

**Issue by mfilin** [vanilophp/framework#138]
hello
how i can to add new setting item in /admin/settings, such as phone, email...

in boot() of AppServiceProvider it added and saved in DB, but in view we have only old data items :(

**Comment by fulopattila122** [comment]
Hi Maksim,

There's no need to manipulate the DB directly, the whole settings part is handled by the [Gears Package](https://konekt.dev/gears/1.x/README)

- To define settings: https://konekt.dev/gears/1.x/defining-settings
- To add the settings to the UI: https://konekt.dev/gears/1.x/building-ui

**Simple Example**

```php
class AppServiceProvider
{
    public function boot()
    {
        // Register (create) the desired settings:
        $settings = $this->app->get('gears.settings_registry');
        $settings->add(new SimpleSetting('app.phone'));
        $settings->add(new SimpleSetting('app.email'));

        // Add the settings to the Admin UI:
        $ui = $this->app->get('appshell.settings_tree_builder');
        $ui->addRootNode('shop', __('Shop'))
            ->addChildNode('shop', 'shop_contact', __('Contact'))
            ->addSettingItem('contact_phone', ['text', ['label' => __('Phone no.')]], 'app.phone')
            ->addSettingItem('contact_email', ['text', ['label' => __('E-mail')]], 'app.email');
    }
}
```

Having this done, you'll have the new entries in the UI on the settings page.

To obtain the value of those settings:

```php
setting('app.phone');
setting('app.email');
```

**Comment by mfilin** [comment]
thx for your example, but in UI my setting is not showing
![image](https://user-images.githubusercontent.com/1892629/198588605-a434e77b-0be9-4f2f-bbc9-61366ebb9c0b.png)

**Comment by mfilin** [comment]
` $settings = $this->app->get('gears.settings_registry');
        $settings->add(new SimpleSetting('app.phone1'));
        $settings->add(new SimpleSetting('app.phone2'));

        Settings::update([
            'app.phone1' => '99999999999',
            'app.phone2' => '99999999999' 
        ]);

        // Add the settings to the Admin UI:
        $ui = $this->app->get('appshell.settings_tree_builder');
        $ui->addRootNode('shop', __('Shop'))
            ->addChildNode('shop', 'shop_contact', __('Contact'))
            ->addSettingItem('contact_phone1', ['text', ['label' => __('Phone1 no.')]], 'app.phone1');`

**Comment by mfilin** [comment]
vanilo 2.x

![image](https://user-images.githubusercontent.com/1892629/198589285-9e66419c-53f0-4f92-ad70-54d233d8473c.png)

**Comment by mfilin** [comment]
found mistake in example 

$ui->addRootNode('shop', __('Shop'))
            ->addChildNode('shop', 'shop_contact', __('Contact'))
            ->addSettingItem('shop_contact', ['text', ['label' => __('Phone1 no.')]], 'app.phone1');

thank for all :)
