### ISSUE TITLE
Master Products cannot allocate attributes

### ISSUE THREAD

**Issue by zmoyi** [vanilophp/framework#139]
Call to undefined method Vanilo\\MasterProduct\\Models\\MasterProduct::assignProperties()

![image](https://user-images.githubusercontent.com/48953751/202332072-850762e3-7a5a-485c-be9d-e3538d213f22.png)

**Comment by zmoyi** [comment]
![image](https://user-images.githubusercontent.com/48953751/202332411-001ed90a-d136-4a3d-9698-0ae74cf60586.png)

**Comment by fulopattila122** [comment]
@zmoyi How did you solve it? :)

**Comment by zmoyi** [comment]
> @zmoyi你是怎么解决的？:)

![image](https://user-images.githubusercontent.com/48953751/202677533-029c6219-ca97-4e90-a1a8-1e817c1f185b.png)
