### ISSUE TITLE
Interface 'Konekt\AppShell\Contracts\Requests\BaseRequest' not found

### ISSUE THREAD

**Issue by parwaizjan** [vanilophp/framework#14]
Soon after installing when I do "php artisan concord:modules -a", I get the following:

PHP Fatal error:  Interface 'Konekt\AppShell\Contracts\Requests\BaseRequest' not found in /home/vagrant/Projects/vanilo.local/www/vendor/vanilo/framework/src/Contracts/Requests/CreateProduct.php on line 17

In CreateProduct.php line 17:
  Interface 'Konekt\AppShell\Contracts\Requests\BaseRequest' not found

Please let me know how I should about it. Thanks and keep up the great work! Love the concept!!

**Comment by fulopattila122** [comment]
How exactly did you install? 

Thanks! Next release is just really close, btw

**Comment by parwaizjan** [comment]
Hi Attila,

I did exactly as mentioned here: https://vanilo.io/docs/0.2/installation

Thanks,
Jan.

**Comment by fulopattila122** [comment]
What is the output of composer show vanilo/* ?

**Comment by parwaizjan** [comment]
vanilo/address   0.2.0 Vanilo Address Module
vanilo/cart      0.2.0 Vanilo Cart Module
vanilo/checkout  0.2.0 Vanilo Checkout Module
vanilo/contracts 0.2.0 Common set of Vanilo Contracts (Interfaces)
vanilo/framework 0.2.0 E-commerce Framework for Laravel
vanilo/order     0.2.2 Vanilo Order Module
vanilo/product   0.2.0 Vanilo Product Module
vanilo/support   0.2.0 Common Vanilo functions, traits, helpers

**Comment by fulopattila122** [comment]
Oh yes, now I know.. AppShell has a BC after v0.9.6

As a quick fix you can add this to your app's composer.json:

```json
require:
  ...
  "konekt/appshell": "0.9.6",
  ...
```

And the remove composer.lock, the vendor dir and run composer install again.

This should fix this issue.
Please report back to me whether it worked.
If all good, I'll fix the 0.2 series accordingly

Cheers

**Comment by parwaizjan** [comment]
Worked like a charm! Thanks.

[Two Thumbs Up]
