### ISSUE TITLE
zones table is missing but referenced...?

### ISSUE THREAD

**Issue by stokic** [vanilophp/framework#145]
https://github.com/vanilophp/framework/blob/master/src/Shipment/resources/database/migrations/2023_03_12_093217_add_zones_foreign_key_to_shipping_methods_table.php

you are creating a fkey but I don't see the table Zones created in any migrations..? :)

**Comment by fulopattila122** [comment]
It's coming from the konekt/address package, referenced here:
- https://github.com/vanilophp/framework/blob/3.6.2/composer.json#L28

more details: https://konekt.dev/address/2.x/zones
