### ISSUE TITLE
How to get access to the sponsor slack channel?

### ISSUE THREAD

**Issue by hirisov** [vanilophp/framework#146]
Hello,

I would like to ask how I can get access to the private slack channel as a sponsor? This is a great project and maybe we can contribute a larger amount to support the development, but would like to discuss the details of that with the developer(s). I sponsored the author on github but haven't got any slack access or other feedback. Should I just wait or there is anything else I should do to get in touch with the team?

thanks, Gabor

**Comment by fulopattila122** [comment]
Hi Gabor,

please use this link to join: https://join.slack.com/share/enQtNTA2NTU1NjczMzc5My1jNzc5MjkxNDhiOWE1OWFhMmM0MjBiZjA1YTUzYTk3YTBmNGI2OGUyN2Y5YjUxNzk0MWE2MjE1NDBmZWM3NDc5

**Comment by fulopattila122** [comment]
In case the link doesn't give a convenient way to connect, please send me your email address; either here or to this ephemeral email address: 6zl4kvosu@mozmail.com.
