### ISSUE TITLE
No vanilo.php configuration file exists

### ISSUE THREAD

**Issue by xhava** [vanilophp/framework#148]
Hi, i have just install the framework and i was reading the option in the Cart documentation section about permatent extra fields, 

but in the docs says that i have to put this in the config/vanilo.php, but this file does not exists, i have to run something to create this file?

**Comment by fulopattila122** [comment]
Just create the file manually. It's the same as any other Laravel config file, ie. It has to return an array:

```php
<?php

return [
    // ...
];
```
