### ISSUE TITLE
option merge_duplicates delete the user cart

### ISSUE THREAD

**Issue by xhava** [vanilophp/framework#149]
Hi, i have a problem with the option merge_duplicates

i create the vanillo.php in config folder

i set this contents:

```php
<?php

return [
    'cart' => [
        'preserve_for_user' => true,
        'merge_duplicates'  => true,
    ]
```

then i began to add a product to the cart without being login 
now the cart is created without a user_id 

![Captura de Pantalla 2023-05-20 a la(s) 1 13 26](https://github.com/vanilophp/framework/assets/4241380/5131ee18-22c8-4641-a800-944c0f29bf33)

then i go to login and when i log in the user the cart records in DB are deleted but the cart items still exists 

![Captura de Pantalla 2023-05-20 a la(s) 1 14 12](https://github.com/vanilophp/framework/assets/4241380/bf689828-58bf-4cc7-853d-a8ab9eb42c10)

i have extended my User model from  \Konekt\User\Models\User

```php
class User extends \Konekt\User\Models\User {

    use HasApiTokens, HasFactory, Notifiable;
```

and in my AppServiceProvider

```php

public function boot(): void
    {
        $this->app->concord->registerModel(\Konekt\User\Contracts\User::class, \App\Models\User::class);
    }
```
  
    
Something special to do, i am missing some configuration?
thanks!

**Comment by fulopattila122** [comment]
Hi!

> i create the vanillo.php in config folder

First of all, it's `vanilo.php` not vanillo; a single L.

Second, what is the behavior you want to achieve?
