### ISSUE TITLE
I can't change default Menu

### ISSUE THREAD

**Issue by thayronarrais** [vanilophp/framework#15]
I comment my code, but continuous showing for me in the admin, 
![image](https://user-images.githubusercontent.com/15815826/41434343-cdcc83d2-6ff1-11e8-8301-b24fbbc83580.png)
CRM, Setting Group is hiding, but shop won't
![image](https://user-images.githubusercontent.com/15815826/41434415-0b2b66d0-6ff2-11e8-9768-6e8ee48cb0c1.png)
where is "Shop" Item ?

**Comment by fulopattila122** [comment]
Hi, I'm travelling at the moment, and I'll take a look into it tomorrow. The general approach is not to comment out menu items but to search and modify/remove them. Please refer to https://github.com/artkonekt/menu/blob/master/README.md

But I'll give you an example romorrow

**Comment by fulopattila122** [comment]
Sorry for the long response, here's the solution:
1. Update the menu component to v1.1 by running in your project folder: `composer update konekt/menu`
2. Add this code to your application's `AppServiceProvider` boot method:
```php
    $menu = \Menu::get('appshell');
    $menu->removeItem('shop');
    $menu->removeItem('crm');
    $menu->removeItem('settings');
```
3. This will [remove the menu items](https://github.com/artkonekt/menu/tree/1.1.0#removing-items):
![image](https://user-images.githubusercontent.com/1162360/42161529-9bff6c12-7dfb-11e8-86ea-3c747bbf1195.png)

## Notes

Please also let me add some notes to the screenshots you posted:

#### Altering Packages
You should [never edit files](https://stackoverflow.com/questions/28136043/modify-files-in-vendor-directory-and-commit-changes-to-composer-lock) in the `vendor/` directory. This applies to any composer package, but Vanilo was especially built with flexibility in mind, so you should be able to replace/modify/disable any part of it. In case not, please submit an issue, like this one :+1: :wink: 

#### Translations
Vanilo, and all underlying components are prepared for translations, there's no need to modify the strings like: `__('Configurações')`. Actually the `__()` [function](https://laravel.com/docs/5.6/localization#retrieving-translation-strings) is exactly for handling translations.

The basic idea is to:
1. Create the file `resources/lang/pt/messages.php`
2. Add the translations like this to it:
```php
<?php

return [
    'Settings' => 'Configurações',
    'Customers' => 'Clientes',
    // etc
];
```
3. Set your language in `config/app.php`: `  'language' => 'pt',`

This is a built in Laravel facility, refer to the [documentation](https://laravel.com/docs/5.6/localization) for more details.

**Comment by thayronarrais** [comment]
thank you!

**Comment by mandala21** [comment]
@fulopattila122 how is path to override vanilo strings to translate?

i try resource/vendor/vanilo/pt/messages.php but without success

**Comment by fulopattila122** [comment]
@mandala21 please open a new issue since this is more than two years old and not even related. I'll answer it there :)
