### ISSUE TITLE
cart item adjustable

### ISSUE THREAD

**Issue by stokic** [vanilophp/framework#150]
Hi, 

I'm not 100% sure, it was quick look but shouldn't this line https://github.com/vanilophp/framework/blob/master/src/Foundation/Models/CartItem.php#L30 
be return $this->total() + $this->adjustments()->total();
?

also here https://github.com/vanilophp/framework/blob/master/src/Foundation/Models/Cart.php#L35 something like:

return $this->items->sum(fn (CartItem $item) => $item->itemsTotal());

then the adjustments are taken into account... 

Thanks

**Comment by fulopattila122** [comment]
Just noticed this after stalebot has closed it. The answer is that `itemsTotal()` comes from [the `Adjustable` interface](https://github.com/vanilophp/framework/blob/3.x/src/Adjustments/Contracts/Adjustable.php#L22).

The method was meant to return the "net" price without any adjustments. As the comment suggests, the name was chosen very stupidly (bravo me :sweat_smile:) and will be changed soon.
