### ISSUE TITLE
Do you plan to release the Vanilo Ecommerce Rest API for self-hosted installs?

### ISSUE THREAD

**Issue by netzknecht** [vanilophp/framework#156]
The cloud version of Vanilo E-Commerce [offers access via Rest API](https://vanilo.cloud/developers/). Is it planed or possible to get it for self-hosted installs so I don't need to implement that for my self?

Thank you and king regards!

**Comment by fulopattila122** [comment]
Hello @netzknecht,

No, we don't have any plans to release that separately. That may change in the future, but not in the upcoming months.
