### ISSUE TITLE
Create GitHub release for each new version

### ISSUE THREAD

**Issue by titouanmathis** [vanilophp/framework#159]
This would allow people to watch and be notified by GitHub when a new release is available. 

This can be automated with an action triggered when a tag is created. The release content can be a link to the entry for the version in the changelog.

I can send a PR if needed.

**Comment by fulopattila122** [comment]
Sounds good!

**Comment by titouanmathis** [comment]
> I mean, I'll be happy to accept that PR :)

That's what I understood :) 

I am off for a few days, I will be able to open a PR when I get back.
