### ISSUE TITLE
Not able to setup vanilo correctly

### ISSUE THREAD

**Issue by daljit3** [vanilophp/framework#16]
I followed all the instructions at https://vanilo.io/docs/0.2/installation but when I try to access myurl/admin/customer I keep getting " Symfony \ Component \ HttpKernel \ Exception \ HttpException
No message" error. Not sure what's going wrong. I did download demo app and that worked fine. 

Only thing I did different was when I created super user then instead of default admin role, I entered in "super admin" which created new role.

**Comment by fulopattila122** [comment]
I'm almost sure it's a 403 error you're getting.
By default only the `admin` role exists, so you should use that initially. Later on you can create arbitrary roles.

**Comment by daljit3** [comment]
@fulopattila122 - I deleted the existing user account and then re-created new one using `php artisan appshell:super` and this time I just entered `admin` in the role. It works fine now. Thank you. 

I suppose you could disable the option to enter another role type there or perhaps put a fix there so that someone else don't make the same mistake as I did.
