### ISSUE TITLE
Change visibility of `ProductSearch` properties from `private` to `proteced`

### ISSUE THREAD

**Issue by netzknecht** [vanilophp/framework#160]
I would like to extend the [`src/Foundation/Search/ProductSearch.php`-class](https://github.com/vanilophp/framework/blob/512ebbf88b4b600041c3eadff9cd2305b41a9e24/src/Foundation/Search/ProductSearch.php)  to add some project specific filter logic. That requires to change the visibility of `ProductSearch` properties from `private` to `proteced` to be able to access in inheriting classes. 

I've changed this in a [commit](https://github.com/vanilophp/framework/commit/508c3b40a6c29bfab62ea400c565b3c25c656634) of my [fork](https://github.com/netzknecht/vanilophp-framework). I didn't create a pull request, because I would like to ask, if there is an other way to accomplish this first?

**Comment by fulopattila122** [comment]
Well there might be some otherways, but I think the easiest is if you change to protected. Feel free to submit the PR.

**Comment by netzknecht** [comment]
Okay, [PR](https://github.com/vanilophp/framework/pull/161) is created.
