### ISSUE TITLE
When can we expect version 4?)

### ISSUE THREAD

**Issue by projct1** [vanilophp/framework#169]

**Comment by fulopattila122** [comment]
Hi There!

It will be released shortly (<2 weeks) after Laravel 11. Most probably in February 2024 (next month)

More details: https://vanilo.io/news/vanilo-4-upcoming

**Comment by fulopattila122** [comment]
Update: Laravel 11 is still under development and will be released most probably mid-March: https://laravel-news.com/laravel-11#content-when-will-laravel-11-be-released

So expect Vanilo 4 to be released by the end of March

**Comment by dmlnc** [comment]
Hello, any updates?

**Comment by fulopattila122** [comment]
If all goes well, it's gonna be this Friday :crossed_fingers: 
But not later than mid-next-week for sure
