### ISSUE TITLE
Composer installation fails

### ISSUE THREAD

**Issue by jsthind** [vanilophp/framework#185]
The composer installation fails on a fresh installation of Laravel 11.1.5

I get the below error message:

 Problem 1
    - laravel/framework is locked to version v11.22.0 and an update of this package was not requested.
    - carbonphp/carbon-doctrine-types 3.2.0 conflicts with doctrine/dbal 3.9.1.
    - vanilo/framework 4.0.0 requires doctrine/dbal ^3.5.1 -> satisfiable by doctrine/dbal[3.5.1, ..., 3.9.1].
    - nesbot/carbon 3.8.0 requires carbonphp/carbon-doctrine-types * -> satisfiable by carbonphp/carbon-doctrine-types[3.2.0].
    - symfony/http-foundation v7.1.3 conflicts with doctrine/dbal 3.5.4.
    - laravel/framework v11.22.0 requires nesbot/carbon ^2.72.2|^3.0 -> satisfiable by nesbot/carbon[3.8.0].
    - laravel/framework v11.22.0 requires symfony/http-foundation ^7.0 -> satisfiable by symfony/http-foundation[v7.1.3].
    - Root composer.json requires vanilo/framework 4.0 -> satisfiable by vanilo/framework[4.0.0].

**Comment by fulopattila122** [comment]
Thanks for the report; looks like there were some dependency changes within the latest Laravel "dot-releases."

We'll take a look into it shortly

**Comment by fulopattila122** [comment]
The documentation has been updated as per @luis-agilstore's suggestion: https://vanilo.io/docs/4.x/installation#with-composer

Thanks to both of you for the report and the solution!
