### ISSUE TITLE
composer install "comand"

### ISSUE THREAD

**Issue by guilhermejuniorjuk** [vanilophp/framework#2]
[Symfony\Component\Debug\Exception\FatalThrowableError]
 Class 'Konekt\Vanilo\Providers\ModuleServiceProvider' not found

**Comment by fulopattila122** [comment]
Thanks for the report. First of all I'll have to note that this package is not even 0.1 yet.

I guess you were following the docs, but that hasn't been updated after the repo/namespace has been moved from Konekt\Vanilo => Vanilo\Framework.

So in general, I kindly ask you to wait until v0.1, that is around the corner:

I want to tag v0.1 as soon as you can:
- define products on admin ✔
- add products to cart on frontend ✔
- make checkout ✔
- have orders on backend ⏳

Right now I'm working with orders and once that's ready, I'll put that all together here (vanilo/framework), update the docs, tag v0.1 and also release some simple demo projects and videos.

**Comment by guilhermejuniorjuk** [comment]
ok thanks
