### ISSUE TITLE
Concord Modules not properly install: Breadcrumds

### ISSUE THREAD

**Issue by ketchank** [vanilophp/framework#20]
Hi,

i followed the instructions of the installation but once i enter the command 

**php artisan concord:modules -a**  

it replies me : 

**Class 'Breadcrumbs' not found**

Could anyone help me ?

**Comment by fulopattila122** [comment]
What PHP version, what Laravel version?
Output of  `composer show`?

**Comment by ketchank** [comment]
![capture pngdd](https://user-images.githubusercontent.com/17270384/45437308-3138e600-b6d2-11e8-93e1-dd28990c25a5.PNG)

**Comment by fulopattila122** [comment]
This doesn't help unfortunately.
Please send the output of these commands:
php -v
composer show

**Comment by ketchank** [comment]
![image](https://user-images.githubusercontent.com/17270384/45470598-ff646580-b74b-11e8-803d-01ee6f2b3980.png)

**Comment by ketchank** [comment]
![image](https://user-images.githubusercontent.com/17270384/45470625-1efb8e00-b74c-11e8-9cde-432416539461.png)

**Comment by ketchank** [comment]
hi @fulopattila122 those are the outputs

today i deleted yesterday's project and restart it over.
and it shows:

![image](https://user-images.githubusercontent.com/17270384/45470689-5702d100-b74c-11e8-9ce1-83abac54ce34.png)

**Comment by fulopattila122** [comment]
As far as I see from your output, the Breadcrumbs plugin is too old for Laravel 5.7 - I have to check that. In general Vanilo doesn't yet support Laravel 5.7, it will be in v0.4 which will be out next week.

Until then please either use Laravel 5.5 / 5.6 or wait until v0.4.

I keep this issue open and will update it, until it fully gets resolved.

Ps.: Thanks for the report!

**Comment by ketchank** [comment]
thanks

I'll try to work on older version and update it once v0.4 is out.

**Comment by fulopattila122** [comment]
Fixed in v0.4. Watch for release of v0.4 - is going to happen in the next few days.

**Comment by fulopattila122** [comment]
Actually now it also works with Vanilo v0.3 and Laravel 5.7.
The problem was in a non-vanilo package (AppShell)

**Comment by ketchank** [comment]
okay .
thanks for the care.
trying it now

**Comment by fulopattila122** [comment]
For an existing install a `composer update konekt/appshell` should do the job (Update AppShell to v0.9.10)

**Comment by ketchank** [comment]
i did restart over and i get an error on the server.

![image](https://user-images.githubusercontent.com/17270384/46000947-aab7d780-c0c7-11e8-8c53-692ba7d949b6.png)

**Comment by fulopattila122** [comment]
That's a separate topic, please open a new issue for that.
