### ISSUE TITLE
datatype conversion error when migrating

### ISSUE THREAD

**Issue by ketchank** [vanilophp/framework#21]
i've been trying to do 

php artisan migrate 

but i got this error

![image](https://user-images.githubusercontent.com/17270384/46003450-346aa380-c0ce-11e8-80b5-4c162ed9a1b6.png)

**Comment by fulopattila122** [comment]
Due to the `json` field type requirement **MySQL 5.7** or higher or **PostgreSQL** is required.
MariaDB is not supported.

This requirement comes from [Spatie's Media Library](https://docs.spatie.be/laravel-medialibrary/v7/requirements)

**Comment by ketchank** [comment]
I did find that article while doing some research on google

As a newbie,
What should I do exactly at this point ?

Sorry for disturbing

**Comment by fulopattila122** [comment]
Use one of the supported database engines: Either MySQL 5.7 or PostgreSQL.

----

This is completely out of Vanilo's scope, but I can give you some suggestions.

My guess is that you are either using MySQL 5.5/5.6 or MariaDB.

You have many options, like:
- In case you have MySQL, you need to upgrade it to version 5.7.
- If you have MariaDB, you can replace it with MySQL 5.7.
- It's also possible to keep your current MariaDB/MySQL installation and add MySQL 5.7 besides them, but on a different port (also change in `config/db.php` accordingly)
- Keep your existing MySQL installation and install Postgres.

If you haven't used Postgres before, and don't have much experience with databases I would suggest to replace you current MariaDB/MySQL installation with MySQL 5.7.
