### ISSUE TITLE
Image paths

### ISSUE THREAD

**Issue by upeksha1996** [vanilophp/framework#23]
I configured vanilo in my project. But when I add product images, it saved as `"http://localhost/storage/5/conversions/sdf-thumbnail.jpg"` which has being saved correctly, but cannot access because it missing port details. correct form should be `http://localhost:8000/storage/5/conversions/sdf-thumbnail.jpg`

**Comment by upeksha1996** [comment]
is it a issue with spatie? Guess the problem is with `$media->getUrl()`

**Comment by upeksha1996** [comment]
Sorry I found the issue. It was about APP_URL in .env file

**Comment by InstantProgramming** [comment]
![capture1](https://user-images.githubusercontent.com/188211/48781570-90bbff00-ecdc-11e8-9808-e6069fc3464f.PNG)
![capture2](https://user-images.githubusercontent.com/188211/48781572-90bbff00-ecdc-11e8-8b04-53f18e119813.PNG)
![capture3](https://user-images.githubusercontent.com/188211/48781575-91549580-ecdc-11e8-8ed7-111729c6a2ac.PNG)
Same issue here, the APP_URL looks good, even in production i have same issue.

**Comment by fulopattila122** [comment]
You have to run `php artisan storage:link`
https://laravel.com/docs/5.7/filesystem#configuration
