### ISSUE TITLE
Error: Method Illuminate\Database\Query\Builder::customers does not exist. 

### ISSUE THREAD

**Issue by learn2develop** [vanilophp/framework#25]
I am trying to insert address for a company and this error comes up above the form: 
Error: Method Illuminate\Database\Query\Builder::customers does not exist. 

The address gets inserted, however there is no link created between customer to address  in customer_addresses table.

Any help on this please?

**Comment by fulopattila122** [comment]
How do you exactly do it?
Can you please post a code example here?

**Comment by learn2develop** [comment]
Sorry I have probably put it in the wrong section. Anyway, I have installed demo and logged in, created customer as company, went into addresses and tried to create address by filling in the details and that is the point where I get the error.

**Comment by learn2develop** [comment]
this is where the exception is thrown 
/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php  line 2817

originating from 
vendor/konekt/appshell/src/Http/Controllers/AddressController.php  method store()

**Comment by fulopattila122** [comment]
Does this happen when you try to add an address in the backend UI?

**Comment by learn2develop** [comment]
Yes

**Comment by fulopattila122** [comment]
Ah, so you've got this in the demo. Please resubmit the issue in vanilophp/demo.
