### ISSUE TITLE
Uploads URL issue

### ISSUE THREAD

**Issue by InstantProgramming** [vanilophp/framework#27]
Hello, i have this issue :

![capture1](https://user-images.githubusercontent.com/188211/48781655-b9dc8f80-ecdc-11e8-8a76-bcaf596fc3c8.PNG)
![capture2](https://user-images.githubusercontent.com/188211/48781656-b9dc8f80-ecdc-11e8-96e6-5daff0b0b29b.PNG)
![capture3](https://user-images.githubusercontent.com/188211/48781657-ba752600-ecdc-11e8-93ae-35422a4a6591.PNG)
 
When uploading Image to Product, i have this path error .
I saw a related Issue but closed, it says it's APP_URL fault but in my case it's not.
Same in Production where APP_URL is good , looks like it missing the "/app/" part of url.

**Comment by fulopattila122** [comment]
Hi Alban,

Running `php artisan storage:link` should fix this problem.
See: https://laravel.com/docs/5.7/filesystem#configuration

**Comment by InstantProgramming** [comment]
Thanks a lot, it solved my issue!
