### ISSUE TITLE
error migrate db

### ISSUE THREAD

**Issue by guilhermejuniorjuk** [vanilophp/framework#3]
`Migration table created successfully.

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 767 bytes (SQL: alter table `users` add unique `
  users_email_unique`(`email`))

In Connection.php line 458:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 767 bytes
`

**Comment by fulopattila122** [comment]
Thank you for the report!

This is apparently this problem:
https://laravel-news.com/laravel-5-4-key-too-long-error

some alternative solutions proposed here:
https://stackoverflow.com/questions/42244541/laravel-migration-error-syntax-error-or-access-violation-1071-specified-key-wa
and here:
https://stackoverflow.com/questions/23786359/laravel-migration-unique-key-is-too-long-even-if-specified

**Comment by guilhermejuniorjuk** [comment]
solved! Thanks.
