### ISSUE TITLE
Issues running yarn run dev

### ISSUE THREAD

**Issue by joaogl** [vanilophp/framework#30]
Hello,

After installation following the documentation the following error showed up upon running yarn run dev:
 
```
ERROR in ./vendor/konekt/appshell/src/resources/assets/sass/appshell.sass
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  &.callout-#{$color} {
 ^
      Top-level selectors may not contain the parent selector "&".
  &.callout-#{$color} {
  ^^^^^^^^^^^^^^^^^^^^
  vendor/konekt/appshell/src/resources/assets/sass/core/_callout.scss 48:3  @import
  stdin 45:9                                                                root stylesheet
```

My versions are the following:

```
vagrant@homestead:~/code/vanillo$ composer show konekt/appshell|grep 'versions'
versions : * 1.3.0
vagrant@homestead:~/code/vanillo$ composer show vanilo/framework|grep 'versions'
versions : * 0.4.0
vagrant@homestead:~/code/vanillo$ composer show laravel/framework|grep 'versions'
versions : * v5.7.20
```

In the mean time I'm going to use your demo repo to run a few tests.

Also, I'm going to be building an e-commerce site for the next 2 months at least with a lot of free time.
I'm interested in a few features that you still have in development/not release so if you need help on those I would gladly help you and this framework while doing also my website.

Thanks,
João Lourenço.

**Comment by fulopattila122** [comment]
Thanks for the report!

What's on the 47th line of `vendor/konekt/appshell/src/resources/assets/sass/core/_callout.scss` ?
It should be exactly like that: https://github.com/artkonekt/appshell/blob/1.3.0/src/resources/assets/sass/core/_callout.scss#L47

**Comment by mzelenkin** [comment]
I have the same problem.

```composer show konekt/appshell|grep 'versions'
versions : * 1.3.0
composer show vanilo/framework|grep 'versions'
versions : * 0.4.0
composer show laravel/framework|grep 'versions'
versions : * v5.7.21
```
Line 47 is the same as the link

**Comment by fulopattila122** [comment]
Looks like we're hitting the very same problem here:
https://github.com/BRACKETS-by-TRIAD/craftable/issues/69

**Comment by andreud** [comment]
a quick solution is to remove the "&"
` &.callout-#{$color} {`
from line 48 of 
`vendor/konekt/appshell/src/resources/assets/sass/core/_callout.scss`
