### ISSUE TITLE
No query results for model [Konekt\Acl\Models\Role]

### ISSUE THREAD

**Issue by learn2develop** [vanilophp/framework#34]
When running this migration
```Migrating: 2018_12_09_193651_create_property_permissions```
Getting this error:
```No query results for model [Konekt\Acl\Models\Role].```

Any advice please?

**Comment by learn2develop** [comment]
I think the problem lies when I delete the ```admin``` role from roles, if the ```admin``` role is in the table it works fine. 

The problem is over this line
```php
$adminRole = RoleProxy::where(['name' => 'admin'])->firstOrFail();
```

I am not using ```admin``` role under such name in my system. Is it possible to move the hard-coded reference ```admin``` from the files to one place (i.e. ```app/concord.php```) please? I have found that the values are hard-coded in the following files

```
2017_06_12_073443_create_appshell_permissions.php
2017_10_19_192447_create_vanilo_permissions.php
```

**Comment by fulopattila122** [comment]
Yes, that's a good point. Still have to figure out how to do it in a backwards compatible manner.

**Comment by fulopattila122** [comment]
If you upgrade konekt/appshell to 1.3.3 or higher and vanilo/framework to 0.5.3 or higher, the problem should be resolved.

**Comment by learn2develop** [comment]
great, thank you, I will have a look
