### ISSUE TITLE
Getting Syntax Error on "php artisan migrate --seed"

### ISSUE THREAD

**Issue by shehrozasmat** [vanilophp/framework#35]
I am getting the error below on runnning "php artisan migrate --seed" 
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MariaDB server  
   version for the right syntax to use near 'json not null, `custom_propertie  
  s` json not null, `responsive_images` json not n' at line 1

**Comment by fulopattila122** [comment]
You're using an old version of MariaDB that doesn't support json fields.
See https://vanilo.io/docs/0.5/installation for supported DB engines.
