### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by jhm-ciberman** [vanilophp/framework#36]
Hello. It seems Vanilo does not support Laravel 5.8 (released today). Can you update the composer.json?

I am in hurry because I need to start a project for a client this week. 
Thanks a lot!

**Comment by jhm-ciberman** [comment]
It seems the problem is with `spatie/laravel-medialibrary`

**Comment by jhm-ciberman** [comment]
I have created an issue https://github.com/spatie/laravel-medialibrary/issues/1398

**Comment by fulopattila122** [comment]
Providing Laravel 5.8 compatibility in such libraries is not only updating composer.json, but also making sure unit and integration tests pass and to resolve compatibility issues.

Vanilo framework along with the modules has composer settings that allow any 5.x version of Laravel.

I label Vanilo releases as "Laravel X" compatible after the compatibility is proven. Expect it within the next few days.

**Comment by jhm-ciberman** [comment]
Hello. There is already a new release for ´spatie/laravel-medialibrary´. But konekt/AppShell does not support it yet. So I will use L5.7 and wait meanwhile. Thanks :)

**Comment by fulopattila122** [comment]
This issue is high prio on my table, so hold on ;)

**Comment by kkrieger85** [comment]
@fulopattila122 Is it possible to add laravel/framework to composer.json to speficy dependencies?

**Comment by fulopattila122** [comment]
Laravel 5.8 compatibility has been fully fixed in Vanilo v0.5.1.
New installations will work from now on.

To fix an existing installation, run:

```bash
composer update 'vanilo/*' konekt/menu konekt/appshell
```

**Comment by fulopattila122** [comment]
@kkrieger85 laravel/framework has been explicitly added to composer.json
