### ISSUE TITLE
Cannot assign category to product

### ISSUE THREAD

**Issue by steveadamsfixedit** [vanilophp/framework#43]
I've installed both the framework and the demo site and I cannot locate or do not have a way to assign a product to a category...I've created test products, and a test category...please advise

Perhaps a site already loaded with demo data?

**Comment by fulopattila122** [comment]
From code: https://vanilo.io/docs/0.5/categorization#assign-taxons-to-products
From admin: go to a product (click on its name) -> Under categories group click Manage
![image](https://user-images.githubusercontent.com/1162360/55213955-5962df00-51f5-11e9-8908-9a4fa1b85ebc.png)

**Comment by steveadamsfixedit** [comment]
Thank you for the quick reply...I do see this capability. Next question, How do I display the products and categories on the front page? Is there a link in the documentation?

**Comment by fulopattila122** [comment]
I think the [demo app](https://github.com/vanilophp/demo/), especially these links can be useful:
- https://github.com/vanilophp/demo/blob/0.5/app/Http/Controllers/ProductController.php
- https://github.com/vanilophp/demo/tree/0.5/resources/views/product
