### ISSUE TITLE
Route to access all products within taxonomy

### ISSUE THREAD

**Issue by Romik90** [vanilophp/framework#45]
Hi. Is there a way to retrieve all products that belongs to taxonomy? 
Route::get('c/{taxonomyName}/{taxon?}', 'ProductController@index')->name('category');
This route works only with taxons. I couldn't find a solution witout rewriting compitelly
ProductController@index method

**Comment by fulopattila122** [comment]
Taxonomy should not be used for this. Taxonomies are like "Category", "Brand" or "Region". Therefore products don't belong to taxonomies like "Brand" but belong to Taxons within a Taxonomy like "Adidas".

**Comment by fulopattila122** [comment]
"Odejda" is clothes if I understand correctly, shapki is "caps".
So in your case Taxonomy should be "Category" and below that
a Taxon "Clothes (Odejda)" which has a child -> "Caps (Shapki)"
All cap products should be added to this taxon (Caps).

**Comment by Romik90** [comment]
So is it possible to use only taxans in my project and exclude taxonomies complitelly?

**Comment by Romik90** [comment]
Ok, having only one taxonomy could be a solution. Thank you!
