### ISSUE TITLE
How not to recreate user's cart after login

### ISSUE THREAD

**Issue by Romik90** [vanilophp/framework#46]
Is there a way how to make an authorized user have only one record in the cart table? I already utilize preserve_for_user config in vanilo.php
![image](https://user-images.githubusercontent.com/17782452/56282200-3a31e000-6117-11e9-8954-d0c15143da8c.png)

**Comment by Romik90** [comment]
I'll try to describe what I want to achieve at the end:
If user is not authorized and add something to cart, it'll be stored in session. Authorized user's cart would be stored in database
If user is not authorized and have some items in his cart, after authorization all items will be added in his cart in db

**Comment by fulopattila122** [comment]
Let's assume that:
- _User3_ has a cart stored in the db assigned with her user_id (3) and that cart contains **Product A**.
- _User3_ is not authenticated and has a cart (in session) that contains **Product B**
- _User3_ logs in

What should her cart contain?

**Comment by Romik90** [comment]
I'd prefer that after loggin the cart will contain both product A and B

**Comment by yusufkandemir** [comment]
The default behaviour is ignoring the last known cart if session cart exists.

I think we can add an option to **merge session cart and last known cart on restore** that is dependent on `vanilo.cart.preserve_for_user`, then check and handle that option in [RestoreCurrentUsersLastActiveCart](https://github.com/vanilophp/cart/blob/0a552d181257d12299484187f2ef76d8c8a39189/src/Listeners/RestoreCurrentUsersLastActiveCart.php#L21). Another option would be changing `vanilo.cart.preserve_for_user` from bool to enum or array with more settings in it to change its behaviour.

**Comment by Romik90** [comment]
Yeah it would be a really great castomization

**Comment by Romik90** [comment]
When could I expect this feature to be implemented? That's what I want most from this framework

**Comment by Romik90** [comment]
I noticed one thing: when I authorized and make order, my cart get removed and it's fine. But when I move to next step in checkout I see my previous cart. I suppose that's cause one person could have more than one cart in database. I consider it as a bag

**Comment by fulopattila122** [comment]
It'll be included in v1.0 which we're at the final week at 🏃

**Comment by fulopattila122** [comment]
What should happen if:

- The session cart contains 1 x "Product A" and the last known cart contains 1 x "Product A"? Should the resulting cart contain 2x Product A or just once?
- The session cart contains 2 x "Product A" and the last known cart contains 2 x "Product A"? Should the resulting cart contain 1, 2 or 3 items of product A?
- The session cart contains 1 x "Product A", 2 x "Product B", whereas the last known cart contains 2 x "Product A" and 1 x "Product B"?

**Comment by fulopattila122** [comment]
A simple merge has been implemented (every item from the old cart will be added to the new one, without any additional check).

See how to use it [in the README](https://github.com/vanilophp/cart/blob/499589060303db29644b5cd08a110dd821f7dfeb/README.md#merge-anonymous-and-user-carts-on-login).

This is available in `1.0@dev`.

**Comment by Romik90** [comment]
> @Romik90 What should happen if:
> 
> * The session cart contains 1 x "Product A" and the last known cart contains 1 x "Product A"? Should the resulting cart contain 2x "Product A" or just once?
> * The session cart contains 1 x "Product A" and the last known cart contains 2 x "Product A"? Should the resulting cart contain 1, 2 or 3 items of "Product A"?
> * The session cart contains 1 x "Product A", 2 x "Product B", whereas the last known cart contains 2 x "Product A" and 1 x "Product B"?

If you ask my oppinion I'd prefer that session cart and database cart merge with preserved amount so in first case resulting cart would contain 2 Product A, in second 3 Product A, and 3 Product A and 3 Product B in the third case

**Comment by yusufkandemir** [comment]
@fulopattila122 maybe these behaviors can be _strategies_ that implement something like `CartMergeBehavior`. Then different people can select different strategies and even maybe some will show a UI that contains different options to the user after logging in.

**Comment by Romik90** [comment]
> This is available in `1.0@dev`.
How to use it?

**Comment by yusufkandemir** [comment]
@Romik90, @fulopattila122 already mentioned about the usage in [his reply](#issuecomment-524656501)

> See how to use it [in the README](https://github.com/vanilophp/cart/blob/499589060303db29644b5cd08a110dd821f7dfeb/README.md#merge-anonymous-and-user-carts-on-login).

from that link:

> #### Merge Anonymous And User Carts On Login
> If the `preserve_for_user` feature is enabled, a previously saved cart will be restored if a user logs back in.
> 
> But what happens when a user already has a new cart with items? By default, the cart gets replaced by the previously saved one.
> 
> If you set the `vanilo.cart.merge_duplicates` config option to true, then the previously saved cart's items will be added to the current cart, preserving the user's new cart as well.
> 
> > This option is disabled by default.
