### ISSUE TITLE
Remove route vanilo.order.create and vanilo.order.edit

### ISSUE THREAD

**Issue by j-dohnalek** [vanilophp/framework#52]
I can not see the `create` function in the [`OrderController`](https://github.com/vanilophp/framework/blob/master/src/Http/Controllers/OrderController.php). Furthermore, the `edit` function is not there as well.

Can you please remove the routes from the admin routes? (unless you plan to implement it in future)

**Comment by fulopattila122** [comment]
Yes, they're planned to be implemented soon.
