### ISSUE TITLE
Incorrect URL generated when rendering uploaded images.

### ISSUE THREAD

**Issue by OpeOnikute** [vanilophp/framework#55]
I uploaded an image to my product, and discovered the image was returning a 404. On checking, I discovered the generated URL was "http://**localhost**/storage/1/conversions/11301016_2560x1440-thumbnail.jpg" instead of "http://**localhost:8000**/storage/1/conversions/11301016_2560x1440-thumbnail.jpg".

The app is running on port 8000 so the images should be rendered from that port.

<img width="1280" alt="Screen Shot 2019-09-09 at 17 14 37" src="https://user-images.githubusercontent.com/13024935/64547902-83ccd280-d325-11e9-872a-7d8989f1cde9.png">
<img width="1280" alt="Screen Shot 2019-09-09 at 17 14 55" src="https://user-images.githubusercontent.com/13024935/64547903-84656900-d325-11e9-922c-1a3532d4ba7a.png">
<img width="1280" alt="Screen Shot 2019-09-09 at 17 15 08" src="https://user-images.githubusercontent.com/13024935/64547906-84656900-d325-11e9-8bd8-7208d980f405.png">

**Comment by fulopattila122** [comment]
You need to set the `APP_URL` in your app's .env file, including the port.

**Comment by OpeOnikute** [comment]
Great. Can you point me to where this is stated in the docs? If not, i'd be happy to help add it.

**Comment by fulopattila122** [comment]
It's Laravel configuration, and the only explicit mention is with Dusk configuration: https://laravel.com/docs/5.8/dusk#installation
