### ISSUE TITLE
Extend admin panel

### ISSUE THREAD

**Issue by Romik90** [vanilophp/framework#57]
Is it possible to extend admin panel for my needs? For example I wanna add google_product_category field in taxonomy editing area
![image](https://user-images.githubusercontent.com/17782452/65948878-c032b080-e443-11e9-8cfe-f20ef9fcdab8.png)

**Comment by Romik90** [comment]
Anybody here?

**Comment by fulopattila122** [comment]
Sorry for the slow pingback. Yes, it's possible. I guess the field is already in the db table.

To add the field to the form, you can simply use Laravel's [override package views](https://laravel.com/docs/5.8/packages#views) feature:
- Create a directory in your app's root folder: `resources/views/vendor/vanilo/taxon`
- Copy `vendor/vanilo/framework/src/resources/views/taxon/_form.blade.php` to the folder created above
- Add the field to the copied file:
![image](https://user-images.githubusercontent.com/1162360/67180381-c7f9cb00-f3d9-11e9-89c6-3c6f2c75a34b.png)
- et voila!
![image](https://user-images.githubusercontent.com/1162360/67180446-faa3c380-f3d9-11e9-9454-9deb4ddad940.png)

**Comment by fulopattila122** [comment]
I've made a how to article based on your question: https://vanilo.io/how-to/customize-admin-add-fields

The article also contains additional steps that describe how to add validation for the new field.

**Comment by Romik90** [comment]
Thank you for reply!
