### ISSUE TITLE
Project delayed or abandoned?

### ISSUE THREAD

**Issue by preliot** [vanilophp/framework#58]
I was wondering if the project is simply delayed or if it's going to be abandoned?

It seems the 0.5 version was the last release and your roadmap suggests the project should be at version 1.2 now. 

I'm interested, because i'm trying to decide if i should use this in my Laravel 6.x project.

**Comment by fulopattila122** [comment]
Yes, the question is absolutely relevant.
We faced some non-technical bumps on the roadmap and 1.0 is delayed.

I'll update the roadmap shortly and will ping you back here.

**Comment by fulopattila122** [comment]
Please see the updated roadmap: https://vanilo.io/docs/0.5/roadmap

**Comment by preliot** [comment]
Congratz on the v1.0 release!

**Comment by fulopattila122** [comment]
1.1 with Laravel 6.0 support is on its way.
TBH we're quite behind our promise to keep up with Laravel releases

**Comment by preliot** [comment]
Do you think this will improve in the near feature? Still on the fence to implement this package and i do need recent Laravel support.

**Comment by fulopattila122** [comment]
Yes, Laravel 6.0 support will arrive by 23 Nov.
Maybe even faster.
