### ISSUE TITLE
[laravel 5.5] Error creating administrator  - The given role or permission should use guard `` instead of `web`.

### ISSUE THREAD

**Issue by youchenlee** [vanilophp/framework#6]
php artisan appshell:super
```
Now you're about to create a new user with all privileges

 E-mail:
 > test@example.com

 Name:
 > test

 Password:
 >

 Role name [admin]:
 >

User 'test@example.com' has been created (id: 2)

In GuardDoesNotMatch.php line 12:

  The given role or permission should use guard `` instead of `web`.
```

Thanks.

**Comment by fulopattila122** [comment]
You need to run php artisan make:auth first

**Comment by youchenlee** [comment]
Oops, my mistake.

`$this->app->concord->registerModel(\Konekt\User\Contracts\User::class, \App\User::class);` should be added to `boot() {}` not `register()` in `AppServiceProvider`

Thank you.
I will close the issue.

**Comment by fulopattila122** [comment]
Was the documentation correct, or does it need to be fixed?

**Comment by youchenlee** [comment]
The document is correct. :)
