### ISSUE TITLE
Call to undefined function str_singular()

### ISSUE THREAD

**Issue by SiCoUK** [vanilophp/framework#61]
When viewing a category (taxonomy) to edit the tree and undefined function error occurs. It appears this file still uses a deprecated Laravel helper feature str_singular().

File: vendor\vanilo\framework\src\resources\views\taxonomy\show.blade.php
Line: 28

I've just started to look at the demo so don't know how you have migrated away from these functions.

It also appears in the following files, mainly related to the taxonomy.
https://github.com/vanilophp/framework/search?q=str_singular%28&unscoped_q=str_singular%28

**Comment by SiCoUK** [comment]
It also appears to be used on resources\views\taxon\create.blade.php

**Comment by SiCoUK** [comment]
Looking around a bit more I'm not sure it's even needed as the category name is what the admin wants it to be, there is no need to change it.

**Comment by fulopattila122** [comment]
Thanks for the report! :bowing_man: 

Update `vanilo/framework` with composer to version 1.1.1 to get this bug fixed.
