### ISSUE TITLE
Thoughts on Product Variants

### ISSUE THREAD

**Issue by SiCoUK** [vanilophp/framework#62]
Can I ask do you have thoughts on how you plan to structure the product variants system?

**Comment by fulopattila122** [comment]
Hi!

I've worked with the following two approaches:

## Variants on Model Level

With this approach, you have a `Product` and one or more `ProductVariant` entities.
[Sylius](https://docs.sylius.com/en/latest/book/products/products.html#variants) for example uses this method.

| Pros                                         | Cons                                                                                 |
|----------------------------------------------|--------------------------------------------------------------------------------------|
| Variants on model level                      | Product model becomes a bit abstract                                                 |
| Likely more DDD                              | Model layer is more complex                                                          |
| Common attributes can be shared in `Product` | Even products without variants must be handled via `ProductVariant` (master variant) |

## Variants as Links

Using this approach, products remain standalone entities and the definition of variants happens solely via defining links between them. This way you define variant groups that link products based on a [property](https://vanilo.io/docs/1.1/properties). The variation is being defined by a variant group, property value, and the products.

| Pros                                                    | Cons                                                     |
|---------------------------------------------------------|----------------------------------------------------------|
| Product remains the final entity                        | Common attributes are duplicated across variant entities |
| Model layer remains simple                              | Requires additional grouping                             |
| No forced _master variant_ on products without variants |                                                          |

I'm leaning towards the latter approach.

I'd like to hear your thoughts as well.

**Comment by r8928** [comment]
+1 for Variants on Model Level
- All products (or variants) are handled in similar way.
- An SKU is treated as an unit (stock keeping **unit**). A variant is a unit not a (group-of-variants) product.

**Comment by fulopattila122** [comment]
I'm about to implement this very soon. I'm thinking about leaving the decision up to the developers of the concrete shops, meaning that both variants will be available, and both will be optional.

**Comment by de-raaf-media** [comment]
Hi Guys. First of all. I see much progress has been made since I last checked in 2018. Vanilophp looks very promising. A while ago I tested version 0.5 because I had to choose a webshop platform for a customer. I decided not to use it yet because product variants were not ready yet. Now, a couple of years later. I have the same choice to make. But the product variants feature is still In progress (since December 2019). I think this is an essential feature for any webshop. I am very curious to hear if this feature will ever roll out. Maybe extend the product properties with the ability to add a price for the property? So a red T-shirt will add two Euros to the price of a default shirt for example?

**Comment by fulopattila122** [comment]
Update on Product Variants. Version 3 is to be released within a day. The documentation has been extended:

Product Variants overview: https://vanilo.io/docs/master/product-variants
The links-based approach: https://vanilo.io/docs/master/links (already implemented part of 3.0)
Master<->Variant approach: https://vanilo.io/docs/master/master-products (incomplete, part of 3.1 - March)

Let me know your thoughts

**Comment by fulopattila122** [comment]
v3.0 has been released
