### ISSUE TITLE
VueJs Frontend Category Grid

### ISSUE THREAD

**Issue by jonathan-martz** [vanilophp/framework#66]
I wrote a small composer module to implement a category grid with vuejs.

Adds vuejs to the frontend (as start for vanillo).
Adds category grid with placeholder data.

https://github.com/jonathan-martz/vanillo-vue

What do you think, is it okay for you or do you have any feedback on this ?

**Comment by fulopattila122** [comment]
Hi Johnathan,

nice idea! Thanks for pinging me.
My only concern is that Vanilo is written with a single L and not double 🙂

How do you plan to get categories data into the app?

**Comment by jonathan-martz** [comment]
https://laravel.com/docs/master/controllers

Laravel Controller with Json response.

Then i can fetch it and parse the data to the component.

Category@view
to get a single category with ids for child categories

Category@collection
category collection to filter

Product@view
single product with data

Product@collection
product collection with a list of products filtered

The Grid should fetch category view.
The Category grid shoudl fetch product collection with category id.
The Product Card should fetch the product view with product id.
Thats the plan, how it works we will see.

With http2 and visible and online check it should work fine.

**Comment by fulopattila122** [comment]
Cool. Let me know if there will be a demo available 👍
