### ISSUE TITLE
Installation issue: Route [login] not defined

### ISSUE THREAD

**Issue by rgasch** [vanilophp/framework#69]
I've followed the install instructions given on 
    https://vanilo.io/docs/1.2/installation

Everything worked well except for this step: 

    php artisan make:auth

which is not a recognized artisan command (I proceeded with the other steps, this may explain my problem). 

Now, when trying to reach the admin login page, I get

    Route [login] not defined

Please advise how to proceed/fix this.

**Comment by fulopattila122** [comment]
Correct observation. This is due to the required dependency of `laravel/ui` package (or something else that provides these functionalities). See also vanilophp/docs#11

Fix is about to come within the next days.

**Comment by rgasch** [comment]
Thank you for your prompt reply! :-)
