### ISSUE TITLE
Product Attributes?

### ISSUE THREAD

**Issue by InkedCurtis** [vanilophp/framework#7]
Is it possible within the `OrderFactory` to assign custom variables/attributes to the order? for example at the moment I've got the following:

```
$factory = app(OrderFactory::class);
$item = [
    'product' => 'product',
    'product_id'   => 3,
    'price' => $this->getPrice(Request::get('platform'), Request::get('amount')),
    'name' => 'Virtual Currency',
    'quantity'     => 1,
];
$factory->createFromDataArray([], [$item]);
```

Would it be possible to maybe add the ability for us to add dynamic elements to the `$item` such as something like so?

```
$factory = app(OrderFactory::class);
$item = [
    'product' => 'product',
    'product_id'   => 3,
    'price' => $this->getPrice(Request::get('platform'), Request::get('amount')),
    'name' => 'Virtual Currency',
    'quantity' => 1,
    'currency_volume' => '5000'
];
$factory->createFromDataArray([], [$item]);
```

**Comment by fulopattila122** [comment]
Yes it's possible. Do you want `currency_volume` to be added only to the order_item or only to the product - or both?

**Comment by InkedCurtis** [comment]
`order_item` would be fine as I'm no longer using the product table since my products are dynamic in price based on order information, doing only `order_item` would be sufficient enough right?

**Comment by fulopattila122** [comment]
It should work with your code, after you have created a migration that adds the `currency_volume` field to the `order_items` table. Please let me know if I was correct/wrong :)

**Comment by InkedCurtis** [comment]
Worked perfect! thanks!

**Comment by InkedCurtis** [comment]
Oh wait, appears that it doesn't insert into the column? maybe it's not a specified column within the model?

**Comment by fulopattila122** [comment]
Exactly. Will fix it shortly and get back to you.

**Comment by InkedCurtis** [comment]
@fulopattila122 Thanks very much! do you have Skype?

**Comment by fulopattila122** [comment]
Run `composer update vanilo/order`. It should update the order component to v0.2.1, which has the desired behavior. Sorry, I don't really use Skype.

**Comment by InkedCurtis** [comment]
I've only got `"vanilo/framework": "^0.2"` inside my composer.json? when running `composer update vanilo/order` I get `Nothing to install or update`, any ideas?

**Comment by InkedCurtis** [comment]
Fixed! ran `composer update vanilo/framework --with-dependencies` 

Thanks for such quick response & action on this!

**Comment by fulopattila122** [comment]
No problem! Feel free to open another issue whenever you get into trouble :)
Usually I respond in the evenings/mornings (Europe/Berlin).

**Comment by InkedCurtis** [comment]
@fulopattila122 Just a quick one, did you know that both these models aren't in the packagist?

```
use Vanilo\Product\Model\Product;
use Vanilo\Order\Model\Order;
```

I'd much rather use the `Models` instead of the `Factory` as it looks much cleaner, any better instructions mate?

**Comment by fulopattila122** [comment]
What do you mean they're not in packagist?

**Comment by InkedCurtis** [comment]
When trying to use both of them like so:

```
<?php

    namespace App\Http\Controllers;
    use Vanilo\Product\Model\Product;
    use Vanilo\Order\Model\Order;

    class myController {

        public function test() {
            $order = Order::create(['number' => 'PO123456']);
        }

    }
```

I get the following:

```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Vanilo\Order\Model\Order' not found
```

**Comment by InkedCurtis** [comment]
^ ignore, was a type in the `use Vanilo\Order\Model\Order;` should have been `use Vanilo\Order\Models\Order;`

**Comment by fulopattila122** [comment]
Sure, you can absolutely use the models directly. Factory is actually to simplify the creation for you.

**Comment by johnnykiyaka** [comment]
hallo guys.is it possible to change currency from usd to ksh??need help

**Comment by fulopattila122** [comment]
> hallo guys.is it possible to change currency from usd to ksh??need help

@johnnykiyaka please open a new issue next time for a new topic. Answer: https://vanilo.io/docs/0.5/configuration#configuring-the-framework
