### ISSUE TITLE
PropertyValueController's FormRequest Errors

### ISSUE THREAD

**Issue by S-DICKSON** [vanilophp/framework#77]
I only made a single issue as it resolves around Form Requests for the same Controller. Could you please look at the following. Thanks!

## CreatePropertyValue
  https://github.com/vanilophp/framework/blob/5f5ec185c9afe4c1023c6213314cad31b616595f/src/Http/Requests/CreatePropertyValue.php#L27
That line is not required as the PropertyValueController@store handles the `property_id` https://github.com/vanilophp/framework/blob/5f5ec185c9afe4c1023c6213314cad31b616595f/src/Http/Controllers/PropertyValueController.php#L42

## UpdatePropertyValue
https://github.com/vanilophp/framework/blob/5f5ec185c9afe4c1023c6213314cad31b616595f/src/Http/Requests/UpdatePropertyValue.php#L27
When no property_id is provided this throws MYSQL FK Constraint. I think this should be `required` not `nullable`.

**Comment by bluetitanboy** [comment]
Can I make a pr for this?

**Comment by fulopattila122** [comment]
What was the problem here you were trying to solve? I mean, I understand the argument, that part is fine, but this code has been working for years without problems in hundreds of installations, so I'd be curious to learn what was the problem you ran into.

**Comment by S-DICKSON** [comment]
I was feature testing the package that's how I discovered this issue.

A user can submit a PropertyValueController::update request with no ```properties,id``` and this will throw MYSQL FK Constraint error so changing it to required will provide better error message to the user.
