### ISSUE TITLE
Problem with php artisan appshell:super command

### ISSUE THREAD

**Issue by orkaite** [vanilophp/framework#78]
When i run php artisan appshell:super command it immediately gets aborted 
![Fiksavimas](https://user-images.githubusercontent.com/65676127/83162235-24605e00-a112-11ea-991d-bdfcd716f14d.PNG)

**Comment by fulopattila122** [comment]
Thx for the report! Which PHP and which Laravel version do you have?

**Comment by orkaite** [comment]
PHP 7.4.0 and Laravel  7.13.0

**Comment by orkaite** [comment]
> Thx for the report! Which PHP and which Laravel version do you have?

PHP 7.4.0 and Laravel 7.13.0

**Comment by fulopattila122** [comment]
Unfortunately, I couldn't reproduce this yet.

Which OS are you running it on? Are you using any virtualization tool like Vagrant/Homestead or Docker?

thx!

**Comment by fulopattila122** [comment]
I think I've found it. It's related to Windows, PHP 7.4.
See issues: symfony/symfony#34702 symfony/symfony#34754 and https://bugs.php.net/bug.php?id=78883

Upgrading PHP to 7.4.1 should solve the problem. Please let me know if it worked.

Thank you!

**Comment by orkaite** [comment]
> I think I've found it. It's related to Windows, PHP 7.4.
> See issues: [symfony/symfony#34702](https://github.com/symfony/symfony/issues/34702) [symfony/symfony#34754](https://github.com/symfony/symfony/issues/34754) and https://bugs.php.net/bug.php?id=78883
> 
> Upgrading PHP to 7.4.1 should solve the problem. Please let me know if it worked.
> 
> Thank you!

Thx it worked.
