### ISSUE TITLE
Extend Products - Adding additional columns

### ISSUE THREAD

**Issue by daniel-farina** [vanilophp/framework#79]
Hello, 

First of all thank you for putting this together. This has so much  potential and I hope to learn it well and eventually contribute.

I'm currently trying to extend products (I'm adding a weight column and a few others) and this is what I did so far: 

- I created a migration to add some columns
- I created the model /App/Products

Now I read the documentation here https://vanilo.io/docs/1.2/models that explains how to extend your model but I find concord to be a bit confusing. I'm have not used it before with Laravel. 

I understand you would need to extend it  but after looking at all the examples from Concord  here https://artkonekt.github.io/concord/#/models?id=detailed-example I ended up even more confused.

I wish there was no Concord to be honest but I know that's currently out of the scope as it was mention on other posts.  

Any guidance is greatly appreciated ! Thanks!

```php
<?php

namespace Vanilo\Product\Models;  //or this -->  namespace App; 

use Vanilo\Product\Models\Product as BaseProduct;
use Vanilo\Product\Contracts\Product as ProductContract;

class Products extends BaseProduct implements ProductContract
{

}
```

I also added this to the boot in appserviceprovider
```php
use App\Products;
use Vanilo\Product\Contracts\Product as ProductContract;
...

        $this->app->concord->registerModel(
            ProductContract::class, Products::class
        );
```

The error:
![image](https://user-images.githubusercontent.com/13665117/83341919-b43f0d00-a2b6-11ea-963b-f8d3aabe51b0.png)

**Comment by daniel-farina** [comment]
I just found instructions here actually under the tutorials section:

https://vanilo.io/how-to/use-custom-models-in-your-application

However it shows undefined method:

![image](https://user-images.githubusercontent.com/13665117/83342305-e56e0c00-a2bb-11ea-8917-53aba2737429.png)


Thanks

**Comment by fulopattila122** [comment]
Basically, you have 2 options to solve it:

1. Either extend `App\Product` from `Vanilo\Framework\Models\Product` or
2. Build your completely own product model: take a look at `Vanilo\Framework\Models\Product` see what interfaces it implements and what traits it uses and cherry-pick the ones you like or implement them yourself.

The quick option is of course the first one.

---
> ℹ **Concord background**: Normally you shouldn't deal too much with Concord, but it's required for the underlying library to know what overridden model do you end up using in your app. So proxies and all the details of Concord can be ignored by application developers, you only have to implement the base interface and let Concord know that you're using your own model for product contract. Afterward you can use your models normally like any other Eloquent model.

**Comment by daniel-farina** [comment]
@fulopattila122 
That worked. I followed the tutorial and was not aware of 
Vanilo\Framework\Models\Product
instead of 
Vanilo\Product\Models\Product

Thank you so much, I'll keep playing with it.

**Comment by fulopattila122** [comment]
Cool, let me know if you stumble upon other issues. I'll simplify the docs based on your feedback :+1:
