### ISSUE TITLE
Cannot change admin prefix

### ISSUE THREAD

**Issue by Sciyguy** [vanilophp/framework#8]
When adding Framework / AppShell configuration for routes -> prefix in concord.php, an exception is raised: 
DaveJamesMiller\Breadcrumbs\Exceptions\DuplicateBreadcrumbException  : Breadcrumb name "home" has already been registered

**Comment by fulopattila122** [comment]
Thanks for the report. I'll look into it either today or on Wednesday.

**Comment by fulopattila122** [comment]
Vanilo doc wasn't specific enough, I've updated it.

In the config file (`concord.php`) you need to include defaults as well. This is due to the way Laravel package configuration works. Quote from https://laravel.com/docs/5.6/packages#configuration:

> This method only merges the first level of the configuration array. If your users partially define a multi-dimensional configuration array, the missing options will not be merged.

So your route definitions in `concord.php` should look something like this:

```php
return [
    'modules' => [
        Konekt\AppShell\Providers\ModuleServiceProvider::class => [
            'ui' => [
                'name' => 'My App Admin',
                'url' => '/myadmin/product' //or whatever your admin start url should be
            ],
            'routes' => [
                'prefix'     => 'myadmin', 
		'middleware' => ['web', 'auth', 'acl'],
		'files'      => ['web'],
		'as' => 'appshell.'
	    ],
        ],
        Vanilo\Framework\Providers\ModuleServiceProvider::class => [
	    'routes' => [
		'prefix'     => 'myadmin', 
		'middleware' => ['web', 'auth', 'acl'],
		'files'      => ['admin'],
		'as' => 'vanilo.'
	    ],
        ]
    ]
];
```

**Comment by Sciyguy** [comment]
Thank you for the clarification. I've tried some variations, but did not include the 'files' option.
