### ISSUE TITLE
MediaCreate has no file size limit

### ISSUE THREAD

**Issue by bluetitanboy** [vanilophp/framework#80]
Hi, there seems to be no limit on the image upload. Please have a look at my test below where I send a request of a 5gb image and the request is accepted and stores it.

https://github.com/vanilophp/framework/blob/5f5ec185c9afe4c1023c6213314cad31b616595f/src/Http/Requests/CreateMedia.php#L31

        $product = app(Product::class)::create(['name' => 'Product 1']);
        $this->assertNull($product->getFirstMedia());

        $postData = [
            'for' => "product",
            'forId' => $product->id,
            '_token' => csrf_token(),
            'images' => UploadedFile::fake()->image('product.jpg')->size(5000000)
        ];

        $this->post(route("vanilo.media.store"), $postData)->assertStatus(302);

        $this->assertNull($product->refresh()->getFirstMedia());

**Comment by fulopattila122** [comment]
You can use media collections to restrict file sizes: 
https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections/#only-allow-certain-files-in-a-collection

See also spatie/laravel-medialibrary#1643

**Comment by learn2develop** [comment]
Hello,  that link returns 404.
![image](https://user-images.githubusercontent.com/6439903/84068024-471b2e00-a9c0-11ea-8466-3af1ea386215.png)

Is there any specific reason you can not restrict the image size in form request?  
https://laravel.com/docs/6.x/validation#rule-size

**Comment by fulopattila122** [comment]
https://github.com/spatie/laravel-medialibrary/issues/1643

https://docs.spatie.be/laravel-medialibrary/v8/working-with-media-collections/defining-media-collections/#only-allow-certain-files-in-a-collection

You can also restrict the file size in the form request if you prefer so: https://vanilo.io/docs/1.2/form-requests#customizing-form-requests
