### ISSUE TITLE
Vanilo on subdomain.

### ISSUE THREAD

**Issue by d-cell** [vanilophp/framework#81]
Hello! Is it possible to move all Vanilo's routes to subdomain? Now, after installation into my existing app, the store is available in myapp.local/shop/index.

The goal i try to achieve is to have the store on a subdomain like shop.myapp.local.

In a regular Laravel routes i can use something like:

`Route::domain('subdomain.myapp.local')->group(function () {...});` , 

but what is the proper way to do it with Vanilo's routes?

Best regards, 
d-cell

**Comment by fulopattila122** [comment]
Does the app serve 2 different domains?

**Comment by fulopattila122** [comment]
Actually, Vanilo itself doesn't contain any frontend routes. `/shop/index` looks to me that it was copied from vanilophp/demo. If that's the case, those routes are just like any other Laravel routes, so you can use the `Route::domain(...)` method too.

**Comment by d-cell** [comment]
Thank you for reply. My app serves a single domain, the only thing i need to do is to locate my store on a subdomain.

You are completely right about `/shop/index`, i borrowed a frontend from the demo app, but just for testing purposes. Glad to here that i can use Vanilo's routes like a regular ones.
