### ISSUE TITLE
Return value of Konekt\Concord\Proxies\ModelProxy::targetClass() must be of the type string, null returned

### ISSUE THREAD

**Issue by victorighalo** [vanilophp/framework#84]
I get this error when i use the role middleware in my routes:

Return value of Konekt\Concord\Proxies\ModelProxy::targetClass() must be of the type string, null returned

`Route::group(['prefix' => 'office', 'middleware' => ['role:admin']], function (){`

**Comment by victorighalo** [comment]
Solved this by updating config/concord.php

```
'modules' => [
        Vanilo\Framework\Providers\ModuleServiceProvider::class,
        Konekt\Acl\Providers\ModuleServiceProvider::class //<- add this,
    ]
```

But all these are not clearly spelt in the docs. So I had to do some digging through. Something seems to be missing somewhere. Initial setup should have all these config.

**Comment by fulopattila122** [comment]
No, you need to add AppShell instead of Acl module, as stated here: https://vanilo.io/docs/1.2/installation#with-composer

**Comment by victorighalo** [comment]
> No, you need to add AppShell instead of Acl module, as stated here: https://vanilo.io/docs/1.2/installation#with-composer

Thanks. I switched to AppShell
