### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by rockymontana** [vanilophp/framework#85]
Hello, I'm wondering if you're working on supporting Laravel 8.0?
If so, when you think it'll be out?

**Comment by fulopattila122** [comment]
Yes, we're working on it. Many of the underlying components have just been upgraded in the last few days to support Laravel 8.

It's important to note that
- only Vanilo 2 will support Laravel 8,
- the v1.x series will be discontinued
- Vanilo 2 will drop Laravel 5 and PHP 7.2 support, ie. it will support PHP 7.3 - 7.4 and Laravel 6-8

The upgrade from Vanilo 1 will be documented and is a comparable effort to a Laravel 5 -> 6 upgrade as an example.

**Comment by martineiler** [comment]
Hi @fulopattila122  
Thank you for your answer. What timeline are you looking into for the Vanilo 2.0 release? Im happy to do some early testing... :-)

**Comment by fulopattila122** [comment]
Thx! October 11 is the target date. Most of the standalone Vanilo components are already working with Laravel 8, if you use the `2.0@dev` constraint in composer. The Framework itself is still having some deps to be harmonized. I'll ping you here once it's in a working condition.

**Comment by mrlinnth** [comment]
Hi @fulopattila122 , I am not sure if I should create a new issue or not.

Which approach between Livewire and Inertia would you recommend to develop Vanilo 2.0 on Laravel 8?

Also cannot wait for 2.0 release :)

**Comment by fulopattila122** [comment]
Hi, the 2.0 components have been released already.

You can use both Inertia or Livewire with Vanilo. The main goal of Vanilo is to provide a truly Laravel solution, hence you can use any Laravel technique you prefer in your application.

**Comment by yusufkandemir** [comment]
@rockymontana Vanilo 2.0 is released on October 31 (17 days ago).

@fulopattila122 I guess this issue can be closed, FYI.

**Comment by fulopattila122** [comment]
Correct, thanks!

Just a minor note: Vanilo 2 was [released in 2 phases](https://vanilo.io/docs/2.x/releases#20-framework):

- All components: October 11
- Framework: October 31
