### ISSUE TITLE
How translate framework?

### ISSUE THREAD

**Issue by mandala21** [vanilophp/framework#87]
# Problem

Based in #15  the framework work with __() for localization. But i cannot found where i place my file for custom the strings.
My app in EN languague then i try place in 
* /resources/lang/vendor/en/en.json
```
{
    "Number": "Número"
}
```
* /resources/lang/vendor/en/en.php
```
<?php
    return [
       'Number' => 'Número'
   ];
```

But dont have success

# Environment
 laravel/framework v7.28.2
vanilo/framework 1.2.1
php 7.3

**Comment by fulopattila122** [comment]
Just put it under `/resources/lang/es.json`, see: https://laravel.com/docs/7.x/localization#using-translation-strings-as-keys

**Comment by mandala21** [comment]
I solve my problem put en.json in folder resources / lang / en.json. But i feeling miss this part in documentation and i think that is very important

**Comment by fulopattila122** [comment]
This is the standard Laravel way, and since there's no deviation from the Laravel common-sense, I don't think we need to repeat the Laravel Documentation.

**Comment by mandala21** [comment]
Maybe for new users in Laravel it is good
