### ISSUE TITLE
Unique key on taxons table for root level taxons

### ISSUE THREAD

**Issue by briska** [vanilophp/framework#89]
Hi, I'm saving some taxons into db and I found out, that the key `taxons_taxonomy_id_slug_parent_id_unique` is not raising error for root level taxons (belonging to the same taxonomy, having the same slug). I think the problem might be their parent_id, which is `NULL`, and as far as I know, there is always some magic behind `NULL` comparisons 🧙

**Comment by fulopattila122** [comment]
Yes, you're right, NULL is being treated differently by most common SQL engines.
This is a known behavior of SQLite, PostgreSQL, MySQL, Oracle, and Firebird:

- https://stackoverflow.com/questions/3712222/does-mysql-ignore-null-values-on-unique-constraints?rq=1
- https://sqlite.org/faq.html#q26

**Comment by fulopattila122** [comment]
Did this answer the question? Shall we close this issue?

**Comment by briska** [comment]
Well, it did, but the problem stays, that taxons on the same level (root) can have same slug and it's a little inconsistent for me... but anyway I should do the validation in my code, so ok for me :)
