### ISSUE TITLE
Upgrade to laravel-medialibrary v9

### ISSUE THREAD

**Issue by LambdaDigamma** [vanilophp/framework#92]
Thanks for this great package and your continous work!

Are there any plans to move to laravel-medialibrary v9 in the near future?
It seems to be not that big of an [upgrade](https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md) but it enables the possibility to use the new `laravel-medialibrary-pro` package and we would stay up to date with the latest medialibrary improvements.

In order to upgrade to v9 I think we would have to only generate a new migration which adds a `generated_conversions` json column.

What is you opinion on that?

**Comment by fulopattila122** [comment]
Media Library v9 support is not a top priority at the moment, but it's doable of course. As I mentioned in the PR, it must be optional, tested, and documented. Feel free to resubmit the PR.

Again, it must be backward compatible and **all** CI checks must pass.

**Comment by fulopattila122** [comment]
Sorry, I forgot to mention, "not a top priority" means I'll likely enable v9 in the next few weeks.

+1 note: MediaLibrary 9 dropped support for Laravel 6, the current LTS.

**Comment by marvinosswald** [comment]
```sql
Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'generated_conversions' can't have a default value (SQL: alter table `media` add `generated_conversions` json not null default '{}')
```

it seems like the default value shouldn't be set and as far as i can tell it isn't set with spaties default package as well, this breaks it for me right now with mysql 5.7 not sure about 8

spaties original: https://github.com/spatie/laravel-medialibrary/blob/master/database/migrations/create_media_table.php.stub#L25

**Comment by fulopattila122** [comment]
@marvinosswald Which Vanilo version are you using?

**Comment by marvinosswald** [comment]
@fulopattila122 latest, `dev-master` as i need php8 support.

**Comment by fulopattila122** [comment]
Now it's been fixed for MySQL/Postgres/SQLite.

I'd like to note that `dev-master` is very unstable at the moment and I recommend waiting until 2.1 is out.
I'm heading towards releasing it by tomorrow, but the chances are high that it will only be ready in the first days of January 2021
