### ISSUE TITLE
Is the admin optional?

### ISSUE THREAD

**Issue by JoshMoreno** [vanilophp/framework#96]
Thanks for creating this and the help. From the docs, it looks straight forward and easy.

I'd like to disable the admin module though as it won't be needed. My use case is we're creating a CMS + e-commerce app and need a unified admin panel. We're planning on using Nova for the admin and would create nova resources for products, product categories, orders, and anything else we may need to wire it up with Vanilo. 

How would one disable the admin panel Vanilo ships with? Or would we need to pull in the individual modules/packages and not use the Vanilo package?

**Comment by fulopattila122** [comment]
Hi Josh,

yes, the admin is optional. You can get rid of it either by:
- not using the framework package, but the individual modules only
- or by disabling it in the Framework.

I suggest the first one, as the Framework is mostly a glue package that integrates the components, but if you plan to use Nova, most of these things you'll likely want to do yourself.

You can still do a quick search within the Framework codebase, but the "glue" part is very lightweight, the majority of its code is the admin itself. So I'd go by adding the components one by one to your app.

Doest this properly answer your question?

**Comment by JoshMoreno** [comment]
Hey sorry for the late reply! Yea that answers it. Thanks
