### ISSUE TITLE
composer installation fails

### ISSUE THREAD

**Issue by kdams** [vanilophp/framework#98]
When installing the latest release via composer, I get the following error message:

  Problem 1
    - vanilo/support 2.1.x-dev requires vanilo/contracts ^2.1.x-dev -> no matching package found.
    - vanilo/support 2.1.0 requires vanilo/contracts ^2.1.x-dev -> no matching package found.
    - vanilo/framework 2.1.1 requires vanilo/support ^2.1 -> satisfiable by vanilo/support[2.1.0, 2.1.x-dev].
    - Installation request for vanilo/framework 2.1.1 -> satisfiable by vanilo/framework[2.1.1].

**Comment by fulopattila122** [comment]
Thanks for the report. That's odd, I've just installed it yesterday evening without any problems.
However, I see the support package has the wrong version constraint. Fixing it immediately.

**Comment by fulopattila122** [comment]
Could you please retry and report back if it has been solved now? Thx!

**Comment by kdams** [comment]
Yes, it is solved! Tnx
