### ISSUE TITLE
Cannot override ProductFinder constructor

### ISSUE THREAD

**Issue by huiyang** [vanilophp/framework#99]
I used my own product table, which have "status" instead of "state" column to store whether it is an active Product. So I will need to override the contructor of the ProductFinder, but then it will give me error as the queryBuiler property is private.

https://github.com/vanilophp/framework/blob/9b7a8242b65abb67a71db8823c30022f704045d2/src/Search/ProductFinder.php#L27

Although i can simply declare my own ProductFinder, but I feel that I love to reuse the ProductFinder here.
May i know what is the reason behind to set the queryBuilder property as private instead of protected?

Thanks.

**Comment by fulopattila122** [comment]
The ProductFinder is just a simple solution to be used out of the box and source for inspiration.
Feel free to declare your own similar class and reuse any of the code from the ProductFinder class.
